count={
    "Bulb Switcher": 1,
    "Happy Number": 17,
    "Two Sum": 114,
    "Climbing Stairs": 35,
    "Best Time to Buy and Sell Stock": 112,
    "Palindrome Number": 32,
    "Rotate Array": 22,
    "Roman to Integer": 35,
    "Maximum Subarray": 53,
    "Delete and Earn": 3,
    "Sum of Values at Indices With K Set Bits": 1,
    "Find Subsequence of Length K With the Largest Sum": 2,
    "Maximum Area of Longest Diagonal Rectangle": 2,
    "Ant on the Boundary": 1,
    "Count Tested Devices After Test Operations": 1,
    "Permutation Difference between Two Strings": 1,
    "Minimum Right Shifts to Sort the Array": 1,
    "Reverse Integer": 22,
    "Longest Palindromic Substring": 73,
    "Largest Number": 17,
    "Merge Sorted Array": 46,
    "Longest Common Prefix": 49,
    "Spiral Matrix": 45,
    "Shortest Palindrome": 5,
    "Sort Integers by The Number of 1 Bits": 3,
    "Majority Element": 19,
    "Longest Substring Without Repeating Characters": 91,
    "3Sum": 64,
    "Find Peak Element": 18,
    "Reverse Words in a String": 18,
    "Perfect Squares": 5,
    "Integer Break": 1,
    "Valid Anagram": 30,
    "Valid Parentheses": 93,
    "Plus One": 14,
    "Product of Array Except Self": 34,
    "Container With Most Water": 50,
    "Fibonacci Number": 10,
    "Remove Duplicates from Sorted Array": 24,
    "Add Two Numbers": 35,
    "Assign Cookies": 2,
    "House Robber": 30,
    "Reverse Vowels of a String": 5,
    "Find First and Last Position of Element in Sorted Array": 30,
    "Longest Increasing Subsequence": 19,
    "Coin Change": 29,
    "Nth Digit": 1,
    "Candy": 12,
    "Count Primes": 9,
    "Merge Intervals": 87,
    "Koko Eating Bananas": 23,
    "Pascal's Triangle": 15,
    "Rotate Image": 33,
    "Perfect Number": 2,
    "Sort Array by Increasing Frequency": 5,
    "Find the Winner of the Circular Game": 5,
    "Next Greater Element I": 7,
    "Valid Palindrome": 27,
    "Edit Distance": 26,
    "Next Permutation": 31,
    "Reverse Linked List": 29,
    "Remove Element": 10,
    "Remove Duplicates from Sorted List": 9,
    "Is Subsequence": 11,
    "Find the Index of the First Occurrence in a String": 19,
    "Peak Index in a Mountain Array": 4,
    "Max Consecutive Ones": 3,
    "Unique Paths": 20,
    "Contains Duplicate": 14,
    "Majority Element II": 5,
    "01 Matrix": 4,
    "Average Value of Even Numbers That Are Divisible by Three": 2,
    "Integer to Roman": 35,
    "Single Number II": 2,
    "Daily Temperatures": 20,
    "Search a 2D Matrix": 20,
    "Count Pairs Whose Sum is Less than Target": 2,
    "Kth Largest Element in an Array": 33,
    "Substrings of Size Three with Distinct Characters": 3,
    "Count Operations to Obtain Zero": 3,
    "Number of Days Between Two Dates": 2,
    "Maximum Depth of Binary Tree": 15,
    "Excel Sheet Column Title": 5,
    "Second Highest Salary": 12,
    "Sqrt(x)": 17,
    "Find Original Array From Doubled Array": 2,
    "N-th Tribonacci Number": 3,
    "Basic Calculator II": 20,
    "Pow(x, n)": 26,
    "Ugly Number II": 2,
    "Intersection of Two Linked Lists": 7,
    "Group Anagrams": 80,
    "How Many Numbers Are Smaller Than the Current Number": 2,
    "Palindromic Substrings": 14,
    "Min Cost Climbing Stairs": 1,
    "Truncate Sentence": 1,
    "Median of Two Sorted Arrays": 42,
    "Binary Search": 7,
    "Make The String Great": 2,
    "Department Top Three Salaries": 5,
    "Replace the Substring for Balanced String": 1,
    "Merge Operations to Turn Array Into a Palindrome": 1,
    "Binary Tree Right Side View": 9,
    "Trapping Rain Water": 80,
    "Search in Rotated Sorted Array": 50,
    "Longest Common Subsequence": 9,
    "Remove Duplicates from Sorted Array II": 14,
    "Asteroid Collision": 19,
    "Fill Missing Data": 1,
    "Count All Valid Pickup and Delivery Options": 2,
    "Parallel Courses III": 7,
    "Invalid Tweets": 2,
    "Reformat Phone Number": 1,
    "Decode String": 29,
    "Number of Divisible Triplet Sums": 5,
    "Merge Two Sorted Lists": 39,
    "Set Matrix Zeroes": 20,
    "Jump Game": 34,
    "Generate Parentheses": 38,
    "Letter Combinations of a Phone Number": 34,
    "Permutations": 24,
    "Jump Game II": 30,
    "Sort Colors": 31,
    "Combination Sum II": 12,
    "First Missing Positive": 40,
    "Valid Sudoku": 30,
    "Merge k Sorted Lists": 41,
    "Subsets": 20,
    "Search Insert Position": 11,
    "Construct Binary Tree from Preorder and Inorder Traversal": 9,
    "Divide Two Integers": 11,
    "String to Integer (atoi)": 16,
    "Reverse Nodes in k-Group": 28,
    "Reverse Linked List II": 16,
    "Binary Tree Zigzag Level Order Traversal": 17,
    "Length of Last Word": 10,
    "Swap Nodes in Pairs": 11,
    "Minimum Window Substring": 30,
    "Largest Rectangle in Histogram": 24,
    "Zigzag Conversion": 22,
    "4Sum": 20,
    "3Sum Closest": 11,
    "Wildcard Matching": 19,
    "Remove Nth Node From End of List": 11,
    "Partition List": 6,
    "Binary Tree Inorder Traversal": 7,
    "Insert Interval": 15,
    "Symmetric Tree": 10,
    "Sudoku Solver": 18,
    "Text Justification": 33,
    "Add Binary": 11,
    "Decode Ways": 21,
    "Longest Valid Parentheses": 19,
    "Same Tree": 11,
    "Balanced Binary Tree": 6,
    "Word Search": 34,
    "Validate Binary Search Tree": 21,
    "Search in Rotated Sorted Array II": 8,
    "Combinations": 7,
    "Unique Paths II": 18,
    "Rotate List": 11,
    "Permutation Sequence": 4,
    "Spiral Matrix II": 10,
    "Substring with Concatenation of All Words": 10,
    "Remove Duplicates from Sorted List II": 7,
    "Count and Say": 14,
    "Restore IP Addresses": 14,
    "N-Queens": 16,
    "Permutations II": 9,
    "Simplify Path": 22,
    "Convert Sorted Array to Binary Search Tree": 5,
    "Construct Binary Tree from Inorder and Postorder Traversal": 1,
    "Combination Sum": 27,
    "Binary Tree Level Order Traversal": 13,
    "Unique Binary Search Trees": 12,
    "Subsets II": 9,
    "Maximal Rectangle": 15,
    "Multiply Strings": 12,
    "Minimum Depth of Binary Tree": 4,
    "Insert Delete GetRandom O(1)": 40,
    "Shortest Uncommon Substring in an Array": 3,
    "Parse Lisp Expression": 2,
    "Design Hit Counter": 13,
    "Insert Delete GetRandom O(1) - Duplicates allowed": 6,
    "String Compression": 19,
    "String Compression III": 2,
    "Number of Recent Calls": 3,
    "Find the Child Who Has the Ball After K Seconds": 1,
    "Capacity To Ship Packages Within D Days": 8,
    "Minimum Absolute Difference": 6,
    "Triangle": 3,
    "Backspace String Compare": 10,
    "Brick Wall": 2,
    "Find Pivot Index": 7,
    "Subarray Product Less Than K": 11,
    "Best Time to Buy and Sell Stock II": 28,
    "Squares of a Sorted Array": 9,
    "Find the Smallest Divisor Given a Threshold": 6,
    "Reverse Substrings Between Each Pair of Parentheses": 1,
    "Permutation in String": 6,
    "Lexicographically Smallest String After Substring Operation": 2,
    "Move Zeroes": 26,
    "Can Place Flowers": 8,
    "Find Median from Data Stream": 23,
    "Kth Smallest Element in a BST": 4,
    "Eliminate Maximum Number of Monsters": 1,
    "Palindrome Pairs": 3,
    "Maximum Profit in Job Scheduling": 17,
    "Flatten 2D Vector": 4,
    "Smallest Common Region": 1,
    "Pour Water": 1,
    "Cheapest Flights Within K Stops": 8,
    "Alien Dictionary": 10,
    "Sliding Puzzle": 2,
    "Simple Bank System": 6,
    "Shortest Path to Get All Keys": 3,
    "Employee Free Time": 7,
    "Word Search II": 16,
    "Maximum Candies You Can Get from Boxes": 2,
    "Contains Duplicate II": 6,
    "Mini Parser": 1,
    "Regular Expression Matching": 22,
    "Pyramid Transition Matrix": 1,
    "IP to CIDR": 2,
    "Strings Differ by One Character": 2,
    "Minimum Number of Vertices to Reach All Nodes": 1,
    "Robot Bounded In Circle": 4,
    "Add Strings": 5,
    "Minimize Rounding Error to Meet Target": 1,
    "Minimum Number of Flips to Convert Binary Matrix to Zero Matrix": 1,
    "Number of Ways to Build House of Cards": 1,
    "Convert to Base -2": 1,
    "Design File System": 5,
    "Single Number": 10,
    "Reverse Bits": 3,
    "Contains Duplicate III": 4,
    "Maximal Square": 20,
    "Design Tic-Tac-Toe": 10,
    "Design Excel Sum Formula": 5,
    "All O`one Data Structure": 5,
    "Time Based Key-Value Store": 21,
    "Shortest Path in Binary Matrix": 3,
    "Making A Large Island": 7,
    "Flatten Nested List Iterator": 10,
    "Fraction to Recurring Decimal": 6,
    "Find the Number of Good Pairs II": 1,
    "Find the Number of Good Pairs I": 1,
    "Minimum Array Changes to Make Differences Equal": 1,
    "Find Polygon With the Largest Perimeter": 1,
    "XOR Queries of a Subarray": 1,
    "N-Repeated Element in Size 2N Array": 1,
    "Construct Binary Search Tree from Preorder Traversal": 1,
    "Longest Palindrome": 3,
    "Pairs of Songs With Total Durations Divisible by 60": 7,
    "Minimum Initial Energy to Finish Tasks": 1,
    "Dice Roll Simulation": 1,
    "Number of Operations to Make Network Connected": 5,
    "Map Sum Pairs": 1,
    "Increasing Decreasing String": 1,
    "Cherry Pickup": 7,
    "Network Delay Time": 2,
    "Create Sorted Array through Instructions": 1,
    "Can Make Palindrome from Substring": 1,
    "Constrained Subsequence Sum": 1,
    "Reduce Array Size to The Half": 1,
    "Minimum Number of Taps to Open to Water a Garden": 6,
    "Number of Different Subsequences GCDs": 1,
    "Minimum Processing Time": 2,
    "Number of Islands": 76,
    "Maximum Star Sum of a Graph": 1,
    "Distance to a Cycle in Undirected Graph": 1,
    "Flood Fill": 5,
    "Critical Connections in a Network": 1,
    "Split Array with Equal Sum": 1,
    "Split Concatenated Strings": 1,
    "Path Sum IV": 1,
    "Valid Parenthesis String": 5,
    "Maximum Number of Pairs in Array": 1,
    "Design a Food Rating System": 2,
    "Watering Plants": 1,
    "Water Bottles": 2,
    "Minimum Time to Complete Trips": 1,
    "Minimum Path Sum": 15,
    "Unique Binary Search Trees II": 6,
    "Recover Binary Search Tree": 6,
    "Interleaving String": 12,
    "Gray Code": 3,
    "Valid Number": 8,
    "N-Queens II": 7,
    "Scramble String": 5,
    "Number of 1 Bits": 5,
    "Subarray Sum Equals K": 25,
    "Number of Divisible Substrings": 4,
    "Design a 3D Binary Matrix with Efficient Layer Tracking": 1,
    "Build Array Where You Can Find The Maximum Exactly K Comparisons": 2,
    "Rotate String": 6,
    "Minimum Deletions to Make Character Frequencies Unique": 3,
    "Maximum Equal Frequency": 1,
    "Percentage of Letter in String": 1,
    "Minimum Number of Operations to Make Array XOR Equal to K": 1,
    "Equal Sum Arrays With Minimum Number of Operations": 1,
    "Find a Value of a Mysterious Function Closest to Target": 1,
    "Maximum XOR After Operations ": 1,
    "Divide an Array Into Subarrays With Minimum Cost II": 2,
    "Divide an Array Into Subarrays With Minimum Cost I": 1,
    "Maximize the Topmost Element After K Moves": 1,
    "Ugly Number III": 1,
    "Minimum Fuel Cost to Report to the Capital": 2,
    "Add Digits": 1,
    "Reconstruct a 2-Row Binary Matrix": 2,
    "The Number of Users That Are Eligible for Discount": 1,
    "The Users That Are Eligible for Discount": 1,
    "Maximum Number of Visible Points": 4,
    "Video Stitching": 2,
    "Course Schedule": 28,
    "Shortest Word Distance": 3,
    "Heaters": 5,
    "Course Schedule II": 23,
    "Search Suggestions System": 13,
    "Flatten Binary Tree to Linked List": 9,
    "Shortest Word Distance II": 2,
    "Flip Equivalent Binary Trees": 1,
    "Number of Distinct Islands": 6,
    "Rotting Oranges": 25,
    "Minesweeper": 4,
    "Insert into a Sorted Circular Linked List": 1,
    "Find the Duplicate Number": 10,
    "Snakes and Ladders": 7,
    "Game of Life": 8,
    "Basic Calculator": 12,
    "Race Car": 2,
    "Construct the Minimum Bitwise Array II": 1,
    "Construct the Minimum Bitwise Array I": 1,
    "Classifying Triangles by Lengths": 1,
    "Minimize OR of Remaining Elements Using Operations": 1,
    "Validate Stack Sequences": 1,
    "Evaluate Reverse Polish Notation": 9,
    "Maximum Number of Balls in a Box": 2,
    "Longest Substring with At Most K Distinct Characters": 5,
    "Shortest Path in a Grid with Obstacles Elimination": 6,
    "Logger Rate Limiter": 7,
    "LRU Cache": 101,
    "Find Duplicate File in System": 3,
    "Word Abbreviation": 2,
    "Best Meeting Point": 4,
    "Shortest Distance from All Buildings": 7,
    "Range Sum Query 2D - Immutable": 6,
    "Design Circular Queue": 8,
    "Cyclically Rotating a Grid": 1,
    "Design HashMap": 7,
    "Jump Game VI": 1,
    "Missing Number": 12,
    "Maximum Length of Subarray With Positive Product": 1,
    "Cycle Length Queries in a Tree": 1,
    "Count Collisions on a Road": 1,
    "Maximize the Confusion of an Exam": 1,
    "Number of People Aware of a Secret": 2,
    "Partition Array Into Two Arrays to Minimize Sum Difference": 6,
    "Possible Bipartition": 5,
    "Stone Game VI": 1,
    "Binary Tree Maximum Path Sum": 22,
    "Find the Count of Monotonic Pairs I": 1,
    "Best Time to Buy and Sell Stock IV": 8,
    "Minimum Insertion Steps to Make a String Palindrome": 1,
    "Maximum Product Subarray": 15,
    "Surrounded Regions": 5,
    "Construct String With Repeat Limit": 2,
    "Find the Town Judge": 2,
    "Reorder List": 5,
    "Inorder Successor in BST II": 1,
    "Rotated Digits": 1,
    "Remove Linked List Elements": 1,
    "Inorder Successor in BST": 3,
    "Moving Average from Data Stream": 6,
    "Missing Element in Sorted Array": 1,
    "Maximum Units on a Truck": 3,
    "Path Sum II": 6,
    "Kth Missing Positive Number": 2,
    "Top K Frequent Elements": 35,
    "Remove All Occurrences of a Substring": 3,
    "Merge In Between Linked Lists": 2,
    "Kth Largest Element in a Stream": 5,
    "Flatten a Multilevel Doubly Linked List": 2,
    "Implement Trie (Prefix Tree)": 17,
    "Maximum Repeating Substring": 3,
    "K Closest Points to Origin": 6,
    "The Number of Rich Customers": 1,
    "Exclusive Time of Functions": 4,
    "Rank Teams by Votes": 4,
    "Design Snake Game": 2,
    "Stock Price Fluctuation ": 4,
    "High-Access Employees": 1,
    "Maximum Good Subarray Sum": 3,
    "Minimum Cost to Convert String I": 1,
    "Minimum Cost to Convert String II": 1,
    "Maximum Square Area by Removing Fences From a Field": 1,
    "Meeting Rooms II": 33,
    "Number of Possible Sets of Closing Branches": 1,
    "Verbal Arithmetic Puzzle": 2,
    "Smallest Missing Non-negative Integer After Operations": 3,
    "Make Lexicographically Smallest Array by Swapping Elements": 2,
    "Minimum Time to Visit a Cell In a Grid": 1,
    "Find the Width of Columns of a Grid": 2,
    "Longest String Chain": 9,
    "Lowest Common Ancestor of a Binary Tree": 13,
    "String Transformation": 3,
    "Online Election": 2,
    "The Time When the Network Becomes Idle": 2,
    "Longest Consecutive Sequence": 30,
    "Russian Doll Envelopes": 3,
    "Count Vowels Permutation": 1,
    "Nth Highest Salary": 3,
    "Crawler Log Folder": 4,
    "Boats to Save People": 6,
    "Maximum Number of Occurrences of a Substring": 3,
    "Lowest Common Ancestor of a Binary Tree III": 2,
    "Find Words That Can Be Formed by Characters": 3,
    "Count Vowel Strings in Ranges": 3,
    "Design Add and Search Words Data Structure": 7,
    "Maximum Path Quality of a Graph": 3,
    "Tallest Billboard": 1,
    "Add Two Integers": 2,
    "Find K Closest Elements": 5,
    "Number of Digit One": 2,
    "Single Element in a Sorted Array": 11,
    "Last Day Where You Can Still Cross": 1,
    "Remove All Adjacent Duplicates in String II": 4,
    "Valid Palindrome II": 7,
    "Integer to English Words": 13,
    "Top K Frequent Words": 11,
    "Missing Number In Arithmetic Progression": 1,
    "Leetflex Banned Accounts": 1,
    "Diameter of Binary Tree": 5,
    "Number of Subarrays That Match a Pattern I": 3,
    "Number of Changing Keys": 1,
    "Distribute Elements Into Two Arrays I": 1,
    "Distribute Elements Into Two Arrays II": 1,
    "Number of Subarrays That Match a Pattern II": 2,
    "Count Prefix and Suffix Pairs II": 3,
    "Count Prefix and Suffix Pairs I": 2,
    "Sliding Window Maximum": 30,
    "Linked List Cycle": 15,
    "Elimination Game": 1,
    "Minimum Size Subarray Sum": 8,
    "Block Placement Queries": 6,
    "Abbreviating the Product of a Range": 1,
    "Add to Array-Form of Integer": 3,
    "Sum of Subarray Minimums": 4,
    "Arithmetic Slices II - Subsequence": 2,
    "Longest Substring with At Least K Repeating Characters": 2,
    "Integer Replacement": 1,
    "Split Array Largest Sum": 9,
    "Arithmetic Slices": 1,
    "Zuma Game": 1,
    "Out of Boundary Paths": 1,
    "Design In-Memory File System": 9,
    "Length of Longest Fibonacci Subsequence": 1,
    "Mark Elements on Array by Performing Queries": 2,
    "Furthest Point From Origin": 1,
    "Count Submatrices with Top-Left Element and Sum Less Than k": 1,
    "Double Modular Exponentiation": 1,
    "Lexicographically Smallest Generated String": 1,
    "Maximum Employees to Be Invited to a Meeting": 2,
    "Minimum Number of Refueling Stops": 6,
    "Isomorphic Strings": 13,
    "Palindrome Linked List": 11,
    "Lexicographical Numbers": 1,
    "Largest Palindromic Number": 3,
    "Car Fleet": 6,
    "Check if an Original String Exists Given Two Encoded Strings": 1,
    "Gas Station": 16,
    "Bus Routes": 7,
    "Evaluate Division": 13,
    "Find the Maximum Sum of Node Values": 2,
    "Maximum Subtree of the Same Color": 1,
    "Path with Maximum Probability": 2,
    "Maximum Profit From Trading Stocks": 3,
    "Maximize Greatness of an Array": 4,
    "Boundary of Binary Tree": 6,
    "Avoid Flood in The City": 1,
    "Rotating the Box": 5,
    "Available Captures for Rook": 1,
    "Squirrel Simulation": 1,
    "Walking Robot Simulation II": 1,
    "Word Break": 25,
    "Falling Squares": 1,
    "Number of Black Blocks": 5,
    "Count Nice Pairs in an Array": 1,
    "Pancake Sorting": 1,
    "Design a Text Editor": 7,
    "The Maze": 3,
    "Count Visited Nodes in a Directed Graph": 1,
    "Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts": 2,
    "Sum of Distances": 1,
    "Minimize Length of Array Using Operations": 2,
    "Minimum Number of Groups to Create a Valid Assignment": 1,
    "Total Cost to Hire K Workers": 4,
    "Find the Count of Monotonic Pairs II": 1,
    "Count Vowel Substrings of a String": 4,
    "Reverse Words in a String III": 6,
    "Check if All Characters Have Equal Number of Occurrences": 1,
    "Find All Anagrams in a String": 8,
    "Best Time to Buy and Sell Stock III": 9,
    "Reward Top K Students": 1,
    "Delete Duplicate Folders in System": 2,
    "Coloring A Border": 1,
    "Two Out of Three": 2,
    "K Highest Ranked Items Within a Price Range": 1,
    "Order Two Columns Independently": 1,
    "Reconstruct Itinerary": 8,
    "Middle of the Linked List": 5,
    "Word Ladder": 18,
    "Event Emitter": 2,
    "Redundant Connection": 2,
    "Diagonal Traverse II": 2,
    "Candy Crush": 6,
    "Count Strictly Increasing Subarrays": 2,
    "Knight Dialer": 2,
    "Smallest Subsequence of Distinct Characters": 2,
    "Remove Duplicate Letters": 5,
    "First Day Where You Have Been in All the Rooms": 1,
    "House Robber II": 9,
    "Sum Game": 2,
    "Number of Good Leaf Nodes Pairs": 2,
    "Sort List": 6,
    "Delete Operation for Two Strings": 1,
    "Open the Lock": 9,
    "Trapping Rain Water II": 5,
    "Compare Version Numbers": 5,
    "Design Memory Allocator": 5,
    "Search a 2D Matrix II": 9,
    "Longest Repeating Character Replacement": 10,
    "Sum of Distances in Tree": 4,
    "Minimum Area Rectangle": 4,
    "H-Index": 3,
    "Find All Good Indices": 2,
    "Degree of an Array": 13,
    "Count Binary Substrings": 5,
    "Maximum Value at a Given Index in a Bounded Array": 1,
    "Partition to K Equal Sum Subsets": 2,
    "Remove Zero Sum Consecutive Nodes from Linked List": 2,
    "Island Perimeter": 1,
    "Divide a String Into Groups of Size k": 1,
    "Number of Unique Subjects Taught by Each Teacher": 1,
    "Reverse Degree of a String": 1,
    "Count Elements With Maximum Frequency": 2,
    "Exchange Seats": 1,
    "Longest Happy String": 5,
    "Minimum Operations to Write the Letter Y on a Grid": 4,
    "Count Alternating Subarrays": 1,
    "Four Divisors": 1,
    "Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit": 7,
    "Split Message Based on Limit": 5,
    "Number of Flowers in Full Bloom": 6,
    "Find the Length of the Longest Common Prefix": 7,
    "Remove Boxes": 3,
    "Binary Tree Paths": 3,
    "Non-overlapping Intervals": 7,
    "Minimum Absolute Difference Between Elements With Constraint": 3,
    "K-diff Pairs in an Array": 2,
    "Number of Adjacent Elements With the Same Color": 3,
    "Get Biggest Three Rhombus Sums in a Grid": 2,
    "Find Servers That Handled Most Number of Requests": 5,
    "Rabbits in Forest": 4,
    "Bulls and Cows": 3,
    "Counter": 1,
    "Find Mirror Score of a String": 1,
    "Minimum Time Difference": 4,
    "House Robber IV": 2,
    "Maximum Erasure Value": 1,
    "Non-decreasing Array": 1,
    "Reformat Date": 4,
    "Detonate the Maximum Bombs": 1,
    "Active Users": 1,
    "Number of Unique Flavors After Sharing K Candies": 1,
    "Predict the Winner": 3,
    "Lucky Numbers in a Matrix": 1,
    "Fizz Buzz": 11,
    "Number of Valid Words in a Sentence": 1,
    "Find Third Transaction": 1,
    "Maximum Difference Between Increasing Elements": 3,
    "Implement Router": 1,
    "Find the Largest Area of Square Inside Two Rectangles": 1,
    "Minimum Cost to Make Array Equal": 3,
    "Number of Equal Count Substrings": 1,
    "Sum of k-Mirror Numbers": 1,
    "Check if Binary String Has at Most One Segment of Ones": 1,
    "Max Points on a Line": 8,
    "Stone Game": 1,
    "Strange Printer": 2,
    "Validate IP Address": 8,
    "Expressive Words": 1,
    "Rising Temperature": 3,
    "Find Minimum in Rotated Sorted Array": 14,
    "Longest Palindromic Subsequence": 3,
    "Min Stack": 26,
    "Count of Integers": 2,
    "Design Browser History": 5,
    "Maximum Product of Two Elements in an Array": 3,
    "Beautiful Arrangement": 5,
    "Remove K Digits": 10,
    "Two Sum IV - Input is a BST": 2,
    "Longest Non-decreasing Subarray From Two Arrays": 1,
    "Minimum Knight Moves": 5,
    "Count Palindromic Subsequences": 3,
    "Minimum Equal Sum of Two Arrays After Replacing Zeros": 3,
    "LFU Cache": 13,
    "Minimum Operations to Make Numbers Non-positive": 2,
    "Number of Good Binary Strings": 2,
    "Maximum Total Damage With Spell Casting": 2,
    "Maximum Length of Repeated Subarray": 1,
    "Minimum Costs Using the Train Line": 1,
    "Best Position for a Service Centre": 1,
    "First Completely Painted Row or Column": 1,
    "Serialize and Deserialize Binary Tree": 10,
    "Length of Longest Subarray With at Most K Frequency": 2,
    "Couples Holding Hands": 1,
    "Meeting Scheduler": 3,
    "Robot Room Cleaner": 3,
    "Design Search Autocomplete System": 4,
    "Sort Items by Groups Respecting Dependencies": 1,
    "Design Front Middle Back Queue": 1,
    "Longest Increasing Path in a Matrix": 6,
    "Minimum Height Trees": 4,
    "Count Ways To Build Good Strings": 1,
    "Transform to Chessboard": 1,
    "Best Time to Buy and Sell Stock with Transaction Fee": 1,
    "Populating Next Right Pointers in Each Node II": 3,
    "Rank Transform of a Matrix": 1,
    "Paint House": 5,
    "Subarray Sums Divisible by K": 4,
    "Word Ladder II": 5,
    "Reorganize String": 10,
    "Egg Drop With 2 Eggs and N Floors": 2,
    "Populating Next Right Pointers in Each Node": 8,
    "Knight Probability in Chessboard": 1,
    "The Skyline Problem": 7,
    "Count Number of Maximum Bitwise-OR Subsets": 1,
    "Number of Visible People in a Queue": 6,
    "Find All Groups of Farmland": 1,
    "Check if Strings Can be Made Equal With Operations II": 1,
    "Check if Strings Can be Made Equal With Operations I": 1,
    "Maximum Performance of a Team": 5,
    "Create Binary Tree From Descriptions": 2,
    "Group Employees of the Same Salary": 1,
    "Minimum Cost to Make at Least One Valid Path in a Grid": 1,
    "Complement of Base 10 Integer": 2,
    "Number Complement": 1,
    "Lexicographically Smallest Equivalent String": 1,
    "Design a Stack With Increment Operation": 4,
    "Reaching Points": 7,
    "Count Subarrays of Length Three With a Condition": 1,
    "Smallest Value of the Rearranged Number": 1,
    "Product Sales Analysis I": 2,
    "Managers with at Least 5 Direct Reports": 4,
    "Students and Examinations": 3,
    "Path With Minimum Effort": 2,
    "Zigzag Iterator": 2,
    "Decode the Message": 2,
    "Check if There is a Valid Partition For The Array": 1,
    "Random Pick with Weight": 15,
    "Number of Orders in the Backlog": 3,
    "Reach a Number": 2,
    "Number of Longest Increasing Subsequence": 2,
    "Count Unreachable Pairs of Nodes in an Undirected Graph": 1,
    "Total Distance Traveled": 1,
    "Camelcase Matching": 1,
    "Subtree of Another Tree": 4,
    "Minimum Time to Eat All Grains": 1,
    "Debounce": 2,
    "Design Authentication Manager": 4,
    "Count Subarrays With Median K": 2,
    "Number of Atoms": 4,
    "Transpose Matrix": 2,
    "Range Module": 2,
    "Split BST": 1,
    "Design Twitter": 3,
    "Shopping Offers": 2,
    "Longest Repeating Substring": 1,
    "Shortest Bridge": 5,
    "Longest Duplicate Substring": 1,
    "Snapshot Array": 7,
    "Distinct Subsequences": 6,
    "Buildings With an Ocean View": 1,
    "Maximum Number of Tasks You Can Assign": 3,
    "Split Strings by Separator": 1,
    "Pacific Atlantic Water Flow": 3,
    "Basic Calculator III": 7,
    "Increasing Triplet Subsequence": 5,
    "Number of Music Playlists": 1,
    "Highest Grade For Each Student": 1,
    "Minimum Moves to Equal Array Elements": 2,
    "Minimum Increment to Make Array Unique": 3,
    "Special Binary String": 4,
    "Frequency of the Most Frequent Element": 4,
    "Intersection of Two Arrays": 12,
    "Ransom Note": 4,
    "Encode and Decode Strings": 3,
    "Synonymous Sentences": 3,
    "Unique Paths III": 2,
    "Minimum Moves to Make Array Complementary": 1,
    "Number of Great Partitions": 2,
    "Longest Palindrome by Concatenating Two Letter Words": 1,
    "Closest Leaf in a Binary Tree": 1,
    "Smallest Range Covering Elements from K Lists": 6,
    "Step-By-Step Directions From a Binary Tree Node to Another": 3,
    "Web Crawler Multithreaded": 5,
    "Count Integers in Intervals": 2,
    "Longest Mountain in Array": 3,
    "Second Degree Follower": 1,
    "Finding Pairs With a Certain Sum": 2,
    "Data Stream as Disjoint Intervals": 1,
    "Design A Leaderboard": 2,
    "Most Common Word": 1,
    "Maximum Depth of N-ary Tree": 1,
    "Valid Word Abbreviation": 4,
    "Maximum Vacation Days": 1,
    "Sliding Window Median": 5,
    "People Whose List of Favorite Companies Is Not a Subset of Another List": 1,
    "Check If It Is a Straight Line": 2,
    "Binary Search Tree to Greater Sum Tree": 3,
    "Greatest Common Divisor of Strings": 3,
    "Odd String Difference": 3,
    "Unique Number of Occurrences": 1,
    "Path Sum": 3,
    "Spiral Matrix III": 1,
    "Maximum Building Height": 1,
    "Binary Tree Cameras": 8,
    "Minimum Size Subarray in Infinite Array": 1,
    "Maximum Subsequence Score": 1,
    "Removing Minimum Number of Magic Beans": 1,
    "Maximum Points Tourist Can Earn": 1,
    "Relative Sort Array": 1,
    "Minimum Cost Walk in Weighted Graph": 1,
    "Max Number of K-Sum Pairs": 1,
    "Maximum Points After Collecting Coins From All Nodes": 1,
    "Maximum Strength of K Disjoint Subarrays": 1,
    "Find the Sum of the Power of All Subsequences": 1,
    "Minimum Deletions to Make String K-Special": 1,
    "Greatest Sum Divisible by Three": 1,
    "Determine the Winner of a Bowling Game": 1,
    "Find the Maximum Divisibility Score": 1,
    "Query Kth Smallest Trimmed Number": 2,
    "Equal Row and Column Pairs": 1,
    "Number of Subarrays With AND Value of K": 1,
    "Number of Substrings Containing All Three Characters": 2,
    "Maximum Deletions on a String": 1,
    "Median of a Row Wise Sorted Matrix": 1,
    "Take Gifts From the Richest Pile": 1,
    "Find Peak Calling Hours for Each City": 1,
    "Shortest String That Contains Three Strings": 1,
    "Minimum Runes to Add to Cast Spell": 1,
    "Minimize Connected Groups by Inserting Interval": 1,
    "Count the Number of Incremovable Subarrays II": 2,
    "K-th Smallest in Lexicographical Order": 3,
    "Painting the Walls": 3,
    "Put Marbles in Bags": 2,
    "Minimum Number of Pushes to Type Word II": 1,
    "Swim in Rising Water": 4,
    "Number of Wonderful Substrings": 1,
    "Task Scheduler": 11,
    "Average Waiting Time": 2,
    "Furthest Building You Can Reach": 5,
    "Min Cost to Connect All Points": 3,
    "Shortest Subarray to be Removed to Make Array Sorted": 2,
    "Find the Shortest Superstring": 1,
    "Maximum OR": 1,
    "Kth Smallest Number in Multiplication Table": 1,
    "Maximum Points You Can Obtain from Cards": 2,
    "Number of Ways to Reorder Array to Get Same BST": 1,
    "Minimum Number of Visited Cells in a Grid": 3,
    "Largest 1-Bordered Square": 3,
    "Implement Stack using Queues": 3,
    "Max Sum of Rectangle No Larger Than K": 1,
    "Make Costs of Paths Equal in a Binary Tree": 1,
    "All Nodes Distance K in Binary Tree": 7,
    "Consecutive Numbers": 3,
    "Find Words Containing Character": 1,
    "Vertical Order Traversal of a Binary Tree": 4,
    "Count Number of Nice Subarrays": 2,
    "Remove Invalid Parentheses": 4,
    "Delete Duplicate Emails": 2,
    "Change Null Values in a Table to the Previous Value": 1,
    "Minimum Time to Repair Cars": 2,
    "Article Views I": 3,
    "Find Customer Referee": 2,
    "Different Ways to Add Parentheses": 2,
    "Smallest K-Length Subsequence With Occurrences of a Letter": 1,
    "Maximum Running Time of N Computers": 2,
    "Maximum Coins Heroes Can Collect": 1,
    "Apply Operations to Maximize Frequency Score": 2,
    "Minimum Operations to Make the Array Increasing": 1,
    "Minimum Operations to Collect Elements": 1,
    "Pour Water Between Buckets to Make Water Levels Equal": 1,
    "Minimize the Difference Between Target and Chosen Elements": 2,
    "Robot Collisions": 3,
    "Collecting Chocolates": 1,
    "Maximum Fruits Harvested After at Most K Steps": 1,
    "Minimize Manhattan Distances": 1,
    "Fruit Into Baskets": 2,
    "Reverse String": 9,
    "Check If Array Pairs Are Divisible by k": 2,
    "Strong Password Checker": 3,
    "Minimum Cost to Buy Apples": 2,
    "Maximum XOR of Two Non-Overlapping Subtrees": 2,
    "Difference Between Maximum and Minimum Price Sum": 2,
    "Number of Sub-arrays With Odd Sum": 1,
    "Find the Winner of an Array Game": 1,
    "Find Longest Awesome Substring": 1,
    "Largest Submatrix With Rearrangements": 2,
    "Max Area of Island": 11,
    "Copy List with Random Pointer": 17,
    "Excel Sheet Column Number": 3,
    "Count Good Nodes in Binary Tree": 2,
    "Reorder Routes to Make All Paths Lead to the City Zero": 2,
    "Palindrome Permutation": 3,
    "IPO": 7,
    "Optimal Partition of String": 1,
    "Clone Graph": 11,
    "Walls and Gates": 7,
    "Most Profit Assigning Work": 2,
    "Check if One String Swap Can Make Strings Equal": 1,
    "Single-Threaded CPU": 2,
    "Minimum Number of Steps to Make Two Strings Anagram": 4,
    "Next Greater Element III": 3,
    "Buddy Strings": 1,
    "Find Nearest Point That Has the Same X or Y Coordinate": 1,
    "Count Sub Islands": 3,
    "Count Nodes With the Highest Score": 2,
    "Immediate Food Delivery II": 3,
    "Immediate Food Delivery I": 1,
    "Interval List Intersections": 5,
    "Mice and Cheese": 1,
    "Subsequence With the Minimum Score": 1,
    "Ways to Make a Fair Array": 5,
    "Minimize Malware Spread": 2,
    "Binary Tree Vertical Order Traversal": 2,
    "Maximum Gap": 1,
    "Shortest Path to Get Food": 1,
    "Analyze User Website Visit Pattern": 2,
    "Find the Celebrity": 7,
    "Number of Provinces": 3,
    "Similar String Groups": 1,
    "Diameter of N-Ary Tree": 1,
    "Counting Words With a Given Prefix": 1,
    "Brace Expansion": 3,
    "Path With Maximum Minimum Value": 1,
    "Number of Closed Islands": 1,
    "Task Scheduler II": 4,
    "Implement Trie II (Prefix Tree)": 1,
    "K-Similar Strings": 1,
    "Count Zero Request Servers": 5,
    "Set Intersection Size At Least Two": 1,
    "Final Prices With a Special Discount in a Shop": 1,
    "Minimum Number of Increments on Subarrays to Form a Target Array": 1,
    "Minimum Falling Path Sum": 2,
    "Shortest Common Supersequence ": 1,
    "Number of Ways to Select Buildings": 1,
    "Partition Equal Subset Sum": 9,
    "Web Crawler": 2,
    "Word Pattern II": 1,
    "Minimize Malware Spread II": 1,
    "Seat Reservation Manager": 2,
    "Check If It Is a Good Array": 3,
    "Word Pattern": 3,
    "Number of Valid Words for Each Puzzle": 1,
    "Word Break II": 9,
    "Grid Illumination": 1,
    "Guess the Word": 3,
    "Number of Islands II": 4,
    "Maximize Sum Of Array After K Negations": 1,
    "Subsequence of Size K With the Largest Even Sum": 1,
    "Counting Elements": 1,
    "Maximize Score After Pair Deletions": 1,
    "Maximal Network Rank": 2,
    "Stone Game VII": 1,
    "Number of Distinct Substrings in a String": 3,
    "Number of Ways to Form a Target String Given a Dictionary": 2,
    "Find All Good Strings": 1,
    "Count Complete Tree Nodes": 1,
    "Encrypt and Decrypt Strings": 1,
    "Minimum Number of People to Teach": 1,
    "K Radius Subarray Averages": 1,
    "Sort Array By Parity": 1,
    "Remove One Element to Make the Array Strictly Increasing": 1,
    "Alternating Digit Sum": 1,
    "Minimum Window Subsequence": 1,
    "Binary Gap": 2,
    "Design Skiplist": 3,
    "Minimize Maximum Pair Sum in Array": 1,
    "Concatenated Words": 1,
    "Longest ZigZag Path in a Binary Tree": 1,
    "Meeting Rooms": 3,
    "Matchsticks to Square": 2,
    "Nearest Exit from Entrance in Maze": 2,
    "Nested List Weight Sum": 4,
    "Maximum Tastiness of Candy Basket": 2,
    "Two Sum II - Input Array Is Sorted": 8,
    "Longest Substring with At Most Two Distinct Characters": 3,
    "Find if Array Can Be Sorted": 1,
    "Wiggle Subsequence": 1,
    "Relative Ranks": 1,
    "Minimum Operations to Make a Uni-Value Grid": 1,
    "Maximum Difference Between Node and Ancestor": 2,
    "First Unique Character in a String": 10,
    "Running Sum of 1d Array": 1,
    "Duplicate Emails": 1,
    "To Be Or Not To Be": 2,
    "Additive Number": 1,
    "Self Dividing Numbers": 1,
    "Stepping Numbers": 1,
    "Angle Between Hands of a Clock": 3,
    "Valid Triangle Number": 2,
    "The kth Factor of n": 2,
    "Minimum Swaps to Group All 1's Together": 1,
    "Divide Players Into Teams of Equal Skill": 3,
    "Break a Palindrome": 5,
    "Minimum One Bit Operations to Make Integers Zero": 3,
    "Most Visited Sector in  a Circular Track": 1,
    "Rearrange Words in a Sentence": 1,
    "Minimum Replacements to Sort the Array": 2,
    "Unique Substrings With Equal Digit Frequency": 1,
    "Valid Word": 2,
    "The Earliest Moment When Everyone Become Friends": 1,
    "Find the City With the Smallest Number of Neighbors at a Threshold Distance": 1,
    "Minimum Number of Swaps to Make the String Balanced": 5,
    "Max Consecutive Ones III": 8,
    "Minimum Number of Chairs in a Waiting Room": 1,
    "Keys and Rooms": 5,
    "Least Number of Unique Integers after K Removals": 3,
    "Count Number of Pairs With Absolute Difference K": 3,
    "Sum of Beauty of All Substrings": 1,
    "Last Substring in Lexicographical Order": 2,
    "Modify the Matrix": 1,
    "Lexicographically Minimum String After Removing Stars": 1,
    "Clear Digits": 1,
    "My Calendar I": 1,
    "Bag of Tokens": 1,
    "Design Movie Rental System": 1,
    "Minimum Number of Coins to be Added": 1,
    "Minimum Cost to Reach City With Discounts": 1,
    "Minimum Limit of Balls in a Bag": 2,
    "The Score of Students Solving Math Expression": 1,
    "Numbers With Same Consecutive Differences": 1,
    "Triples with Bitwise AND Equal To Zero": 1,
    "Minimum Total Cost to Make Arrays Unequal": 2,
    "Cherry Pickup II": 2,
    "Minimum Adjacent Swaps for K Consecutive Ones": 1,
    "Create Maximum Number": 1,
    "Dungeon Game": 1,
    "Burst Balloons": 5,
    "Maximum Width of Binary Tree": 1,
    "Find K-th Smallest Pair Distance": 2,
    "Number of Students Unable to Eat Lunch": 1,
    "Cut Off Trees for Golf Event": 1,
    "Amount of Time for Binary Tree to Be Infected": 7,
    "Filling Bookcase Shelves": 1,
    "Car Pooling": 3,
    "Maximum Sum Circular Subarray": 2,
    "Minimum Number of Arrows to Burst Balloons": 3,
    "Minimum Cost For Tickets": 6,
    "Path Sum III": 3,
    "Last Stone Weight": 4,
    "Patching Array": 2,
    "Course Schedule III": 2,
    "Percentage of Users Attended a Contest": 1,
    "Number of Ways to Paint N × 3 Grid": 1,
    "Longest Unequal Adjacent Groups Subsequence II": 1,
    "Longest Subarray With Maximum Bitwise AND": 1,
    "Longest Unequal Adjacent Groups Subsequence I": 2,
    "Find Three Consecutive Integers That Sum to a Given Number": 1,
    "Maximum Product of Three Numbers": 7,
    "Maximize Sum of Weights after Edge Removals": 1,
    "Minimum Cost of Buying Candies With Discount": 2,
    "Delete Columns to Make Sorted": 1,
    "Minimum Cost to Set Cooking Time": 1,
    "Minimum Remove to Make Valid Parentheses": 4,
    "Concatenation of Array": 1,
    "Maximum Number of Potholes That Can Be Fixed": 1,
    "Number of Steps to Reduce a Number in Binary Representation to One": 2,
    "Best Time to Buy and Sell Stock with Cooldown": 3,
    "Number of Spaces Cleaning Robot Cleaned": 1,
    "Path with Maximum Gold": 1,
    "Minimum Number of Food Buckets to Feed the Hamsters": 3,
    "Count of Smaller Numbers After Self": 1,
    "Minimum Moves to Spread Stones Over Grid": 2,
    "Cinema Seat Allocation": 2,
    "Remove All Adjacent Duplicates In String": 5,
    "Number of Connected Components in an Undirected Graph": 3,
    "The Number of Full Rounds You Have Played": 1,
    "Last Visited Integers": 1,
    "Widest Vertical Area Between Two Points Containing No Points": 1,
    "Dot Product of Two Sparse Vectors": 3,
    "Convert an Array Into a 2D Array With Conditions": 1,
    "Minimize the Maximum of Two Arrays": 1,
    "Valid Arrangement of Pairs": 2,
    "Construct Smallest Number From DI String": 2,
    "Power of Three": 1,
    "Minimum Cost Homecoming of a Robot in a Grid": 2,
    "Range Product Queries of Powers": 2,
    "Keep Multiplying Found Values by Two": 1,
    "Count Number of Texts": 1,
    "Successful Pairs of Spells and Potions": 1,
    "Determine if Two Events Have Conflict": 1,
    "Maximum XOR of Two Numbers in an Array": 1,
    "Pascal's Triangle II": 2,
    "Fraction Addition and Subtraction": 3,
    "Group Shifted Strings": 2,
    "Missing Ranges": 2,
    "Graph Valid Tree": 5,
    "Wiggle Sort": 2,
    "3Sum Smaller": 2,
    "Lowest Common Ancestor of a Binary Search Tree": 6,
    "Read N Characters Given read4 II - Call Multiple Times": 2,
    "Paint Fence": 1,
    "Flip Game": 1,
    "Binary Tree Postorder Traversal": 1,
    "Strobogrammatic Number": 1,
    "Peeking Iterator": 1,
    "Closest Binary Search Tree Value II": 2,
    "Unique Word Abbreviation": 1,
    "Flip Game II": 1,
    "Insertion Sort List": 1,
    "Factorial Trailing Zeroes": 1,
    "Bitwise AND of Numbers Range": 1,
    "Rank Scores": 1,
    "Read N Characters Given Read4": 1,
    "Find Minimum in Rotated Sorted Array II": 1,
    "Range Sum Query - Mutable": 1,
    "Binary Tree Level Order Traversal II": 3,
    "Adding Two Negabinary Numbers": 1,
    "Repeated DNA Sequences": 3,
    "Vowel Spellchecker": 1,
    "Decode the Slanted Ciphertext": 1,
    "Sum of Left Leaves": 1,
    "Set Mismatch": 1,
    "Maximum Palindromes After Operations": 2,
    "Collect Coins in a Tree": 2,
    "Sell Diminishing-Valued Colored Balls": 2,
    "Minimum Number of Operations to Make X and Y Equal": 1,
    "Game Play Analysis V": 1,
    "Game Play Analysis I": 1,
    "Game Play Analysis II": 1,
    "Game Play Analysis III": 1,
    "Game Play Analysis IV": 1,
    "Minimum Number of Operations to Sort a Binary Tree by Level": 1,
    "Construct the Longest New String": 2,
    "Get Watched Videos by Your Friends": 1,
    "Print Words Vertically": 1,
    "Add Bold Tag in String": 1,
    "Find Candidates for Data Scientist Position": 1,
    "Maximize Items": 1,
    "Maximum Points Inside the Square": 1,
    "Count the Number of Powerful Integers": 2,
    "Chalkboard XOR Game": 1,
    "Brightest Position on Street": 4,
    "Maximize the Number of Partitions After Operations": 2,
    "Parsing A Boolean Expression": 1,
    "Sort an Array": 2,
    "Minimum Distance to the Target Element": 1,
    "Maximum Matrix Sum": 1,
    "Three Equal Parts": 1,
    "Remove 9": 1,
    "Minimum Recolors to Get K Consecutive Black Blocks": 1,
    "Maximum Binary String After Change": 1,
    "24 Game": 2,
    "Find the K-Sum of an Array": 1,
    "Detect Pattern of Length M Repeated K or More Times": 1,
    "Add Edges to Make Degrees of All Nodes Even": 1,
    "Longest Path With Different Adjacent Characters": 2,
    "Maximum Total Importance of Roads": 1,
    "Convert Integer to the Sum of Two No-Zero Integers": 1,
    "Number of Steps to Reduce a Number to Zero": 1,
    "Maximum 69 Number": 1,
    "Maximum Score From Grid Operations": 1,
    "Remove Comments": 1,
    "Number of Valid Subarrays": 1,
    "Binary Tree Pruning": 1,
    "Sum of Two Integers": 1,
    "Count Ways to Group Overlapping Ranges": 1,
    "Minimum Operations to Make All Array Elements Equal": 2,
    "Minimum Operations to Make Median of Array Equal to K": 1,
    "Maximum Profitable Triplets With Increasing Prices I": 1,
    "Find The First Player to win K Games in a Row": 1,
    "Activity Participants": 1,
    "Find Products of Elements of Big Array": 1,
    "Type of Triangle": 1,
    "Taking Maximum Energy From the Mystic Dungeon": 1,
    "Find Occurrences of an Element in an Array": 2,
    "Find the Array Concatenation Value": 1,
    "Minimum Levels to Gain More Points": 1,
    "Sort the Students by Their Kth Score": 1,
    "Minimum Length of String After Operations": 1,
    "Maximum Profitable Triplets With Increasing Prices II": 1,
    "Get Equal Substrings Within Budget": 1,
    "Minimum Suffix Flips": 2,
    "Maximum Sum of Distinct Subarrays With Length K": 2,
    "Numbers With Repeated Digits": 2,
    "Count Pairs Of Similar Strings": 1,
    "Shortest and Lexicographically Smallest Beautiful String": 3,
    "Minimum Swaps to Group All 1's Together II": 2,
    "Flipping an Image": 1,
    "Flip String to Monotone Increasing": 2,
    "Find The Original Array of Prefix Xor": 3,
    "Find All Possible Stable Binary Arrays II": 1,
    "Removing Stars From a String": 1,
    "Minimum Number of Flips to Make the Binary String Alternating": 1,
    "Rearrange Array to Maximize Prefix Score": 2,
    "Find Longest Calls": 1,
    "132 Pattern": 2,
    "The Employee That Worked on the Longest Task": 2,
    "Count Number of Teams": 1,
    "Minimum Operations to Reduce an Integer to 0": 3,
    "Prime In Diagonal": 1,
    "Score After Flipping Matrix": 1,
    "Find the Safest Path in a Grid": 2,
    "Time Taken to Cross the Door": 1,
    "Maximum Side Length of a Square with Sum Less than or Equal to Threshold": 1,
    "Sum of Even Numbers After Queries": 1,
    "Binary Tree Tilt": 1,
    "Minimum Cost to Split an Array": 1,
    "Find Players With Zero or One Losses": 2,
    "Check if Every Row and Column Contains All Numbers": 3,
    "Online Stock Span": 1,
    "Count Nodes Equal to Average of Subtree": 2,
    "Find the Minimum and Maximum Number of Nodes Between Critical Points": 2,
    "Find the Maximum Factor Score of Array": 1,
    "Count Almost Equal Pairs I": 1,
    "Subrectangle Queries": 2,
    "Find Building Where Alice and Bob Can Meet": 1,
    "Minimum Reverse Operations": 1,
    "Count the Number of Ideal Arrays": 1,
    "Transform Array by Parity": 1,
    "Maximum Sum of Subsequence With Non-adjacent Elements": 1,
    "Eat Pizzas!": 1,
    "Determine the Minimum Sum of a k-avoiding Array": 1,
    "Sort the People": 1,
    "Number of Beautiful Integers in the Range": 1,
    "Longest Well-Performing Interval": 1,
    "Maximum Product After K Increments": 1,
    "Maximum Segment Sum After Removals": 1,
    "Minimum Total Distance Traveled": 1,
    "Minimum Addition to Make Integer Beautiful": 1,
    "Number of Nodes With Value One": 1,
    "Can Convert String in K Moves": 1,
    "The Number of Beautiful Subsets": 1,
    "Stone Game VIII": 1,
    "Maximum Number of Consecutive Values You Can Make": 1,
    "Find the Minimum Possible Sum of a Beautiful Array": 1,
    "Maximize the Minimum Game Score": 1,
    "Largest Number After Mutating Substring": 1,
    "Find the Number of Subsequences With Equal GCD": 1,
    "Rearrange Array Elements by Sign": 1,
    "Palindrome Partitioning": 4,
    "Create a DataFrame from List": 1,
    "Implement Queue using Stacks": 4,
    "To Lower Case": 1,
    "Kids With the Greatest Number of Candies": 1,
    "Replace Employee ID With The Unique Identifier": 2,
    "Maximum Score Words Formed by Letters": 1,
    "Average Time of Process per Machine": 3,
    "Partition Labels": 2,
    "Maximum Number of Robots Within Budget": 1,
    "Subarray With Elements Greater Than Varying Threshold": 1,
    "Maximum Number of Events That Can Be Attended": 4,
    "Maximum Nesting Depth of the Parentheses": 1,
    "Find Consecutive Integers from a Data Stream": 1,
    "Most Profitable Path in a Tree": 2,
    "Number of Substrings With Fixed Ratio": 1,
    "Maximum Total Beauty of the Gardens": 1,
    "Destroy Sequential Targets": 1,
    "Length of the Longest Subsequence That Sums to Target": 1,
    "Basic Calculator IV": 2,
    "Maximum Difference Score in a Grid": 1,
    "Make String Anti-palindrome": 1,
    "Unique Email Addresses": 3,
    "Next Greater Element II": 2,
    "Largest Plus Sign": 1,
    "Get the Maximum Score": 2,
    "Minimum Time to Break Locks I": 1,
    "Minimum Time to Break Locks II": 1,
    "Range Addition II": 1,
    "Stickers to Spell Word": 1,
    "Find the Derangement of An Array": 1,
    "1-bit and 2-bit Characters": 2,
    "Remove Colored Pieces if Both Neighbors are the Same Color": 5,
    "Check Whether Two Strings are Almost Equivalent": 3,
    "Determine Color of a Chessboard Square": 1,
    "Minimum Swaps to Make Strings Equal": 1,
    "Suspicious Bank Accounts": 1,
    "Button with Longest Push Time": 1,
    "Display Table of Food Orders in a Restaurant": 2,
    "Check if Number Has Equal Digit Count and Digit Value": 2,
    "Maximum Number of Points From Grid Queries": 1,
    "Lexicographically Smallest String After Applying Operations": 1,
    "Lexicographically Smallest String After a Swap": 1,
    "Reverse Odd Levels of Binary Tree": 2,
    "Find Resultant Array After Removing Anagrams": 1,
    "Count Numbers with Unique Digits": 1,
    "Minimum Cost to Connect Sticks": 1,
    "Shuffle an Array": 3,
    "Minimum String Length After Removing Substrings": 2,
    "Minimum Insertions to Balance a Parentheses String": 1,
    "Ugly Number": 1,
    "Sum of Subarray Ranges": 2,
    "Count Common Words With One Occurrence": 1,
    "Walking Robot Simulation": 3,
    "Minimum Time to Make Array Sum At Most x": 1,
    "Stream of Characters": 2,
    "Find the Grid of Region Average": 1,
    "Maximize the Number of Target Nodes After Connecting Trees I": 1,
    "Maximize the Number of Target Nodes After Connecting Trees II": 1,
    "Maximum Twin Sum of a Linked List": 1,
    "Find Bottom Left Tree Value": 1,
    "Merge Nodes in Between Zeros": 1,
    "Find the Substring With Maximum Cost": 1,
    "Trim a Binary Search Tree": 1,
    "Largest Combination With Bitwise AND Greater Than Zero": 1,
    "Add Two Numbers II": 1,
    "Longest Cycle in a Graph": 1,
    "Operations on Tree": 1,
    "Find Closest Node to Given Two Nodes": 1,
    "Node With Highest Edge Score": 1,
    "Longest Subsequence With Decreasing Adjacent Difference": 1,
    "Largest Color Value in a Directed Graph": 1,
    "Shortest Path in a Weighted Tree": 1,
    "Maximum Points in an Archery Competition": 1,
    "Minimum Moves to Reach Target with Rotations": 1,
    "Alert Using Same Key-Card Three or More Times in a One Hour Period": 2,
    "Subdomain Visit Count": 4,
    "Maximum Product of First and Last Elements of a Subsequence": 1,
    "Maximum Swap": 1,
    "Time Needed to Buy Tickets": 2,
    "Find the Sum of Encrypted Integers": 1,
    "Longest Strictly Increasing or Strictly Decreasing Subarray": 1,
    "Smallest String With A Given Numeric Value": 1,
    "Diagonal Traverse": 5,
    "Frog Jump": 5,
    "Minimum Cost to Cut a Stick": 2,
    "Max Stack": 4,
    "Nested List Weight Sum II": 1,
    "Find Leaves of Binary Tree": 1,
    "Binary Tree Upside Down": 1,
    "Factor Combinations": 1,
    "Sort Transformed Array": 1,
    "Valid Perfect Square": 2,
    "Kth Smallest Product of Two Sorted Arrays": 1,
    "Second Minimum Node In a Binary Tree": 1,
    "Can I Win": 1,
    "Shortest Word Distance III": 2,
    "Sparse Matrix Multiplication": 2,
    "Find K Pairs with Smallest Sums": 1,
    "Sum of Square Numbers": 2,
    "Time to Cross a Bridge": 1,
    "Maximize Total Tastiness of Purchased Fruits": 1,
    "Find Largest Value in Each Tree Row": 1,
    "Maximum Number of Non-overlapping Palindrome Substrings": 3,
    "Minimum Deletions to Make Array Divisible": 1,
    "Two Sum III - Data structure design": 1,
    "Binary Search Tree Iterator": 2,
    "Minimum Time to Type Word Using Special Typewriter": 2,
    "Distribute Candies": 1,
    "Shortest Unsorted Continuous Subarray": 1,
    "Longest Harmonious Subsequence": 2,
    "Largest Time for Given Digits": 1,
    "The Number of Good Subsets": 2,
    "Groups of Strings": 1,
    "Find the Original Typed String I": 1,
    "Minimum Operations to Make Array Values Equal to K": 1,
    "Maximum White Tiles Covered by a Carpet": 1,
    "Closest Subsequence Sum": 2,
    "Convert Sorted List to Binary Search Tree": 4,
    "Check Completeness of a Binary Tree": 1,
    "Water and Jug Problem": 2,
    "Process Tasks Using Servers": 3,
    "Find Minimum Time to Finish All Jobs": 3,
    "Coordinate With Maximum Network Quality": 2,
    "Number of Transactions per Visit": 1,
    "Reachable Nodes With Restrictions": 1,
    "Sum Of Special Evenly-Spaced Elements In Array": 1,
    "Longest Ideal Subsequence": 1,
    "Unique Substrings in Wraparound String": 1,
    "Count Subarrays With Fixed Bounds": 4,
    "Maximum Number of Alloys": 1,
    "Reshape the Matrix": 1,
    "Earliest Second to Mark Indices I": 1,
    "Keyboard Row": 1,
    "Earliest Second to Mark Indices II": 1,
    "Count Anagrams": 1,
    "Minimum Cost Tree From Leaf Values": 2,
    "Pass the Pillow": 1,
    "Minimum Edge Reversals So Every Node Is Reachable": 1,
    "Convert Binary Number in a Linked List to Integer": 3,
    "Maximal Score After Applying K Operations": 1,
    "Minimum Operations to Form Subsequence With Target Sum": 1,
    "Count the Number of Square-Free Subsets": 1,
    "Maximum Genetic Difference Query": 1,
    "Minimum Total Space Wasted With K Resizing Operations": 1,
    "Make the XOR of All Segments Equal to Zero": 1,
    "Minimum Time Visiting All Points": 1,
    "Minimum XOR Sum of Two Arrays": 1,
    "Queens That Can Attack the King": 1,
    "Sum of Remoteness of All Cells": 1,
    "Maximum Value of an Ordered Triplet II": 1,
    "Maximum Value of an Ordered Triplet I": 1,
    "Number of Submatrices That Sum to Target": 1,
    "Valid Phone Numbers": 1,
    "Minimize the Maximum Difference of Pairs": 2,
    "Count Largest Group": 1,
    "Minimum Subsequence in Non-Increasing Order": 1,
    "Max Difference You Can Get From Changing an Integer": 2,
    "Airplane Seat Assignment Probability": 2,
    "Battleships in a Board": 2,
    "Number of Ways to Build Sturdy Brick Wall": 1,
    "Broken Calculator": 2,
    "Find Array Given Subset Sums": 1,
    "Number of Ways to Wear Different Hats to Each Other": 1,
    "Count Integers With Even Digit Sum": 1,
    "Find the Integer Added to Array I": 1,
    "Find the Integer Added to Array II": 1,
    "Minimum Substring Partition of Equal Character Frequency": 1,
    "Construct String with Minimum Cost": 1,
    "Maximum Total Reward Using Operations I": 1,
    "Maximum Total Reward Using Operations II": 1,
    "Shortest Subarray With OR at Least K II": 1,
    "Shortest Subarray With OR at Least K I": 1,
    "Right Triangles": 1,
    "Symmetric Coordinates": 1,
    "Redistribute Characters to Make All Strings Equal": 1,
    "Merge Two Binary Trees": 1,
    "Minimum Cost to Move Chips to The Same Position": 1,
    "Best Team With No Conflicts": 1,
    "Find Subarrays With Equal Sum": 1,
    "Minimum Number of Lines to Cover Points": 1,
    "Find the Longest Valid Obstacle Course at Each Position": 1,
    "Make K-Subarray Sums Equal": 1,
    "Contiguous Array": 1,
    "Stamping The Sequence": 1,
    "Coin Change II": 1,
    "Minimum Operations to Reduce X to Zero": 1,
    "Subarrays with K Different Integers": 2,
    "Steps to Make Array Non-decreasing": 1,
    "Count of Range Sum": 1,
    "Score of Parentheses": 2,
    "Maximum Number of Removable Characters": 2,
    "Maximum Earnings From Taxi": 1,
    "Deepest Leaves Sum": 1,
    "Repeated Substring Pattern": 1,
    "Minimum Time to Collect All Apples in a Tree": 1,
    "Target Sum": 3,
    "Minimum Moves to Equal Array Elements II": 1,
    "Count Number of Ways to Place Houses": 1,
    "Decoded String at Index": 2,
    "Champagne Tower": 1,
    "Special Array II": 1,
    "Special Array I": 1,
    "Minimum Number of Days to Make m Bouquets": 1,
    "Reconstruct Original Digits from English": 3,
    "Summary Ranges": 3,
    "Cache With Time Limit": 2,
    "Employee Bonus": 2,
    "Average Salary Excluding the Minimum and Maximum Salary": 1,
    "Design Graph With Shortest Path Calculator": 2,
    "Design a Todo List": 1,
    "Line Reflection": 2,
    "Check If Word Is Valid After Substitutions": 1,
    "Partitioning Into Minimum Number Of Deci-Binary Numbers": 1,
    "Grumpy Bookstore Owner": 1,
    "Delivering Boxes from Storage to Ports": 1,
    "Detect Cycles in 2D Grid": 1,
    "Maximum Sum of an Hourglass": 2,
    "Online Majority Element In Subarray": 1,
    "Swap For Longest Repeated Character Substring": 1,
    "Maximum Frequency Stack": 4,
    "Rectangle Area": 1,
    "Double a Number Represented as a Linked List": 1,
    "Minimum Add to Make Parentheses Valid": 3,
    "Convert Binary Search Tree to Sorted Doubly Linked List": 1,
    "Counting Bits": 1,
    "Verify Preorder Sequence in Binary Search Tree": 2,
    "Linked List Random Node": 1,
    "Print in Order": 1,
    "Delete Node in a Linked List": 3,
    "All Possible Full Binary Trees": 1,
    "Rectangle Overlap": 2,
    "Sort Characters By Frequency": 3,
    "Swapping Nodes in a Linked List": 2,
    "Count the Number of Good Subsequences": 4,
    "Fair Candy Swap": 2,
    "Kth Smallest Element in a Sorted Matrix": 4,
    "Design SQL": 1,
    "Largest Local Values in a Matrix": 1,
    "Largest 3-Same-Digit Number in String": 2,
    "Reverse Prefix of Word": 1,
    "Bank Account Summary": 1,
    "Invert Binary Tree": 2,
    "Number of Unique Good Subsequences": 1,
    "The Number of the Smallest Unoccupied Chair": 1,
    "Flatten Deeply Nested Array": 4,
    "House Robber III": 2,
    "Monotonic Array": 1,
    "Department Highest Salary": 3,
    "Find Beautiful Indices in the Given Array I": 2,
    "Find Beautiful Indices in the Given Array II": 2,
    "Range Sum Query - Immutable": 1,
    "Selling Pieces of Wood": 1,
    "Maximum Size Subarray Sum Equals k": 1,
    "Construct Quad Tree": 1,
    "Accounts Merge": 6,
    "All Ancestors of a Node in a Directed Acyclic Graph": 1,
    "Find the Longest Equal Subarray": 1,
    "Maximum Length of a Concatenated String with Unique Characters": 1,
    "Count the Number of Vowel Strings in Range": 1,
    "Maximum Number of Integers to Choose From a Range I": 1,
    "Number of Valid Move Combinations On Chessboard": 1,
    "Time Needed to Rearrange a Binary String": 2,
    "Maximum Frequency Score of a Subarray": 1,
    "Minimum Non-Zero Product of the Array Elements": 1,
    "Maximum Number of Integers to Choose From a Range II": 1,
    "Paint House III": 1,
    "Maximum Sum Obtained of Any Permutation": 1,
    "Count Array Pairs Divisible by K": 1,
    "Smallest Greater Multiple Made of Two Digits": 1,
    "Loud and Rich": 1,
    "Meeting Rooms III": 2,
    "Lexicographically Smallest Palindrome": 1,
    "Maximum Population Year": 2,
    "Invalid Transactions": 2,
    "Minimum Number of Removals to Make Mountain Array": 1,
    "Minimize Maximum of Array": 1,
    "Number of Unequal Triplets in Array": 1,
    "Find Indices With Index and Value Difference I": 1,
    "Find Indices With Index and Value Difference II": 1,
    "Longest Nice Subarray": 1,
    "Linked List Cycle II": 3,
    "Execute Asynchronous Functions in Parallel": 1,
    "Maximum Profit of Operating a Centennial Wheel": 1,
    "Minimum Bit Flips to Convert Number": 1,
    "Viewers Turned Streamers": 1,
    "Frequencies of Shortest Supersequences": 1,
    "Smallest String With Swaps": 1,
    "Maximum Amount of Money Robot Can Earn": 1,
    "Check if Point Is Reachable": 1,
    "Count the Number of Arrays with K Matching Adjacent Elements": 1,
    "Most Stones Removed with Same Row or Column": 3,
    "Queue Reconstruction by Height": 1,
    "Reachable Nodes In Subdivided Graph": 1,
    "Distribute Coins in Binary Tree": 1,
    "Split Array into Consecutive Subsequences": 1,
    "Find Duplicate Subtrees": 2,
    "Decode Ways II": 1,
    "Complete Binary Tree Inserter": 1,
    "Magnetic Force Between Two Balls": 2,
    "Find All Possible Recipes from Given Supplies": 3,
    "Make Sum Divisible by P": 2,
    "Optimal Account Balancing": 5,
    "Count Subarrays With Score Less Than K": 1,
    "Expression Add Operators": 1,
    "Shortest Way to Form String": 1,
    "Longest Word in Dictionary": 1,
    "Find Median Given Frequency of Numbers": 1,
    "Jump Game III": 3,
    "Minimize Result by Adding Parentheses to Expression": 2,
    "The Number of Weak Characters in the Game": 1,
    "Is Graph Bipartite?": 2,
    "Non-negative Integers without Consecutive Ones": 1,
    "Find All Duplicates in an Array": 1,
    "Top Travellers": 1,
    "Weather Type in Each Country": 1,
    "Evaluate Boolean Expression": 1,
    "Restaurant Growth": 1,
    "Advantage Shuffle": 1,
    "K-th Smallest Prime Fraction": 1,
    "Minimum Sideway Jumps": 1,
    "Extra Characters in a String": 1,
    "Count Unguarded Cells in the Grid": 1,
    "Market Analysis I": 1,
    "Market Analysis II": 1,
    "Max Chunks To Make Sorted": 1,
    "Determine if Two Strings Are Close": 1,
    "Most Beautiful Item for Each Query": 2,
    "Find the K-Beauty of a Number": 2,
    "Valid Square": 1,
    "Maximum Number of Ones": 1,
    "Power of Four": 3,
    "Count the Number of Fair Pairs": 2,
    "Find Winner on a Tic Tac Toe Game": 3,
    "Power of Two": 4,
    "Count Square Sum Triples": 1,
    "Construct Target Array With Multiple Sums": 1,
    "Encode Number": 1,
    "Find Numbers with Even Number of Digits": 1,
    "3Sum With Multiplicity": 1,
    "Subtract the Product and Sum of Digits of an Integer": 1,
    "Exam Room": 1,
    "Range Frequency Queries": 1,
    "Maximum Number of Words You Can Type": 1,
    "Sort the Matrix Diagonally": 2,
    "Number of Subarrays with Bounded Maximum": 1,
    "Two Best Non-Overlapping Events": 1,
    "Minimum Deletions to Make String Balanced": 1,
    "Number of Ways to Buy Pens and Pencils": 1,
    "Evaluate the Bracket Pairs of a String": 1,
    "Teemo Attacking": 1,
    "Better Compression of String": 1,
    "Design Spreadsheet": 1,
    "Employee Importance": 2,
    "Maximize Amount After Two Days of Conversions": 1,
    "Max Increase to Keep City Skyline": 1,
    "Restore the Array From Adjacent Pairs": 1,
    "Count Good Meals": 2,
    "Ways to Split Array Into Three Subarrays": 2,
    "Check if There is a Valid Path in a Grid": 1,
    "Capital Gain/Loss": 1,
    "Count the Number of Consistent Strings": 1,
    "Defanging an IP Address": 1,
    "Maximize Distance to Closest Person": 6,
    "Number of Trusted Contacts of a Customer": 1,
    "Group the People Given the Group Size They Belong To": 1,
    "Minimum Falling Path Sum II": 1,
    "Image Smoother": 4,
    "Minimum Number of Frogs Croaking": 2,
    "Maximum Points After Enemy Battles": 1,
    "Stamping the Grid": 1,
    "Alice and Bob Playing Flower Game": 1,
    "Count Lattice Points Inside a Circle": 1,
    "Distribute Candies Among Children III": 1,
    "Distribute Candies Among Children II": 2,
    "Distribute Candies Among Children I": 1,
    "Find X Value of Array I": 1,
    "Find Longest Special Substring That Occurs Thrice II": 1,
    "Find the Sum of Subsequence Powers": 1,
    "Existence of a Substring in a String and Its Reverse": 1,
    "Maximize Subarray Sum After Removing All Occurrences of One Element": 1,
    "Find X Value of Array II": 1,
    "Manhattan Distances of All Arrangements of Pieces": 1,
    "Building H2O": 2,
    "Prefix and Suffix Search": 1,
    "Design Bounded Blocking Queue": 2,
    "Height Checker": 1,
    "Check If a Number Is Majority Element in a Sorted Array": 1,
    "Beautiful Towers I": 1,
    "Beautiful Towers II": 1,
    "Smallest Subtree with all the Deepest Nodes": 1,
    "Range Addition": 1,
    "Number of Matching Subsequences": 2,
    "2 Keys Keyboard": 1,
    "Alternating Groups I": 1,
    "Alternating Groups II": 1,
    "Minimum Cost of a Path With Special Roads": 1,
    "Maximum Height by Stacking Cuboids ": 1,
    "Minimize Deviation in Array": 1,
    "Number of Paths with Max Score": 1,
    "Number of Nodes in the Sub-Tree With the Same Label": 1,
    "Stone Game IX": 1,
    "Faulty Keyboard": 1,
    "Minimum Number of Operations to Make String Sorted": 1,
    "Guess Number Higher or Lower": 1,
    "Count Increasing Quadruplets": 1,
    "Maximum Students Taking Exam": 1,
    "Count the Number of Infection Sequences": 2,
    "Movie Rating": 2,
    "Leftmost Column with at Least a One": 1,
    "Maximum Number of Weeks for Which You Can Work": 2,
    "Monotone Increasing Digits": 1,
    "Lexicographically Smallest String After Operations With Constraint": 1,
    "Number of Distinct Roll Sequences": 1,
    "Find Minimum Diameter After Merging Two Trees": 1,
    "Sum Root to Leaf Numbers": 2,
    "Vowels of All Substrings": 1,
    "Reverse Words in a String II": 1,
    "Check if a Parentheses String Can Be Valid": 1,
    "Maximum Count of Positive Integer and Negative Integer": 1,
    "Count Pairs in Two Arrays": 2,
    "Memoize": 1,
    "Encode and Decode TinyURL": 1,
    "Find Users With Valid E-Mails": 1,
    "Minimized Maximum of Products Distributed to Any Store": 1,
    "Peaks in Array": 1,
    "Design Log Storage System": 1,
    "One Edit Distance": 3,
    "Closest Binary Search Tree Value": 1,
    "Bricks Falling When Hit": 2,
    "Least Operators to Express Number": 1,
    "Combination Sum IV": 1,
    "Largest Merge Of Two Strings": 1,
    "Ternary Expression Parser": 1,
    "Minimum Number of Keypresses": 1,
    "Minimum Time to Complete All Tasks": 1,
    "Verifying an Alien Dictionary": 2,
    "Reorder Data in Log Files": 1,
    "Build Binary Expression Tree From Infix Expression": 1,
    "Custom Sort String": 1,
    "Longest Arithmetic Subsequence": 1,
    "Calculate Amount Paid in Taxes": 1,
    "Maximum Number of Upgradable Servers": 1,
    "Minimum Array Length After Pair Removals": 1,
    "Find the Maximum Length of a Good Subsequence I": 1,
    "Find the Maximum Length of a Good Subsequence II": 1,
    "Throne Inheritance": 1,
    "Longest Univalue Path": 3,
    "Remove Sub-Folders from the Filesystem": 2,
    "Parallel Courses": 1,
    "Leaf-Similar Trees": 1,
    "Reverse Only Letters": 3,
    "Minimum Number of Swaps to Make the Binary String Alternating": 1,
    "Second Largest Digit in a String": 1,
    "Subtree Removal Game with Fibonacci Tree": 1,
    "Reducing Dishes": 1,
    "Linked List in Binary Tree": 1,
    "Check if Array Is Sorted and Rotated": 2,
    "Leetcodify Friends Recommendations": 1,
    "Leetcodify Similar Friends": 1,
    "Minimum Edge Weight Equilibrium Queries in a Tree": 1,
    "Apply Operations on Array to Maximize Sum of Squares": 1,
    "Next Greater Numerically Balanced Number": 1,
    "Maximize Score After N Operations": 1,
    "Maximum Score of Non-overlapping Intervals": 1,
    "Minimum Time to Revert Word to Initial State II": 1,
    "Choose Edges to Maximize Score in a Tree": 1,
    "Number of Same-End Substrings": 1,
    "Create Components With Same Value": 1,
    "Minimum Time to Revert Word to Initial State I": 1,
    "Apply Bitwise Operations to Make Strings Equal": 1,
    "Maximum Subarray Sum After One Operation": 1,
    "Sum of Matrix After Queries": 1,
    "Count Valid Paths in a Tree": 1,
    "Number of Dice Rolls With Target Sum": 1,
    "Minimum Penalty for a Shop": 1,
    "Satisfiability of Equality Equations": 2,
    "Maximize Area of Square Hole in Grid": 1,
    "Minimum Value to Get Positive Step by Step Sum": 1,
    "Maximum Score From Removing Substrings": 1,
    "Minimum Number of Work Sessions to Finish the Tasks": 1,
    "Two City Scheduling": 1,
    "Maximum Length of Pair Chain": 1,
    "Product of the Last K Numbers": 2,
    "Count the Digits That Divide a Number": 1,
    "Maximum Ascending Subarray Sum": 1,
    "Remove Letter To Equalize Frequency": 1,
    "Minimum Cuts to Divide a Circle": 1,
    "Minimum Operations to Exceed Threshold Value I": 1,
    "Minimum Operations to Exceed Threshold Value II": 1,
    "Palindrome Partitioning IV": 1,
    "Bitwise ORs of Subarrays": 1,
    "Toeplitz Matrix": 1,
    "Sum of Unique Elements": 1,
    "Number of Employees Who Met the Target": 1,
    "Big Countries": 1,
    "Cousins in Binary Tree": 1,
    "Minimum Factorization": 1,
    "Implement Rand10() Using Rand7()": 1,
    "Find Followers Count": 1,
    "Minimum Changes To Make Alternating Binary String": 1,
    "Maximum Number of Balloons": 2,
    "Largest Perimeter Triangle": 1,
    "Longest Substring Of All Vowels in Order": 1,
    "Count Paths That Can Form a Palindrome in a Tree": 1,
    "Minimum Number of K Consecutive Bit Flips": 1,
    "Count Pairs of Connectable Servers in a Weighted Tree Network": 2,
    "Number of Bit Changes to Make Two Integers Equal": 1,
    "Maximum GCD-Sum of a Subarray": 1,
    "Find Closest Number to Zero": 1,
    "Find Target Indices After Sorting Array": 1,
    "Form Smallest Number From Two Digit Arrays": 1,
    "Find All Numbers Disappeared in an Array": 1,
    "Longest Subarray of 1's After Deleting One Element": 3,
    "Minimum Difference Between Highest and Lowest of K Scores": 1,
    "Count Square Submatrices with All Ones": 1,
    "Find the Longest Balanced Substring of a Binary String": 1,
    "String Compression II": 1,
    "Substring XOR Queries": 1,
    "Handling Sum Queries After Update": 1,
    "Bitwise XOR of All Pairings": 1,
    "Minimum Time to Kill All Monsters": 1,
    "Find Common Characters": 1,
    "Baseball Game": 1,
    "Minimum Length of Anagram Concatenation": 2,
    "Apply Operations to Make Sum of Array Greater Than or Equal to k": 2,
    "Partition Array Into Three Parts With Equal Sum": 1,
    "Maximum Number of Vowels in a Substring of Given Length": 2,
    "Sum of Digit Differences of All Pairs": 1,
    "Minimum Number of Operations to Make Word K-Periodic": 1,
    "Number of Subsequences That Satisfy the Given Sum Condition": 1,
    "Minimum Number of Operations to Satisfy Conditions": 1,
    "Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold": 1,
    "Minimum Difficulty of a Job Schedule": 1,
    "Count Good Triplets": 1,
    "Number of Ways to Earn Points": 1,
    "Intervals Between Identical Elements": 1,
    "Maximum Good People Based on Statements": 1,
    "Univalued Binary Tree": 1,
    "Create a Session Bar Chart": 1,
    "Design a File Sharing System": 1,
    "Toss Strange Coins": 1,
    "Maximum Subarray Sum with One Deletion": 1,
    "Minimum Space Wasted From Packaging": 1,
    "Escape a Large Maze": 1,
    "Sorting Three Groups": 1,
    "As Far from Land as Possible": 2,
    "Maximum Area Rectangle With Point Constraints I": 1,
    "Maximum Area Rectangle With Point Constraints II": 1,
    "Make a Positive Array": 1,
    "Number of Subarrays With LCM Equal to K": 1,
    "Dota2 Senate": 1,
    "Deep Merge of Two Objects": 1,
    "Design Parking System": 1,
    "Check if the Sentence Is Pangram": 1,
    "Minimum Area Rectangle II": 1,
    "Shifting Letters II": 1,
    "Count Pairs With XOR in a Range": 1,
    "Flower Planting With No Adjacent": 1,
    "How Many Apples Can You Put into the Basket": 1,
    "Array Transformation": 1,
    "Hexspeak": 1,
    "Count Substrings with Only One Distinct Letter": 1,
    "Count Number of Homogenous Substrings": 1,
    "Apply Operations to Make String Empty": 1,
    "Length of Longest V-Shaped Diagonal Segment": 1,
    "Split the Array": 1,
    "Create Target Array in the Given Order": 1,
    "Match Alphanumerical Pattern in Matrix I": 1,
    "Earliest Possible Day of Full Bloom": 1,
    "Divisor Game": 1,
    "Two Furthest Houses With Different Colors": 1,
    "Find Score of an Array After Marking All Elements": 1,
    "Find Palindrome With Fixed Length": 1,
    "Make Array Non-decreasing or Non-increasing": 1,
    "Divide Intervals Into Minimum Number of Groups": 1,
    "Minimum Number of Operations to Make Arrays Similar": 1,
    "Count Good Triplets in an Array": 1,
    "Minimum Operations to Make Array Equal II": 1,
    "Number of Ways to Separate Numbers": 1,
    "The Winner University": 1,
    "Binary Tree Longest Consecutive Sequence": 1,
    "Number of Accounts That Did Not Stream": 1,
    "Largest Magic Square": 1,
    "Minimum Moves to Reach Target Score": 1,
    "Team Scores in Football Tournament": 1,
    "Tournament Winners": 1,
    "Best Sightseeing Pair": 1,
    "Delete Characters to Make Fancy String": 1,
    "Last Person to Fit in the Bus": 1,
    "Divide Array in Sets of K Consecutive Numbers": 1,
    "Minimum Number of Steps to Make Two Strings Anagram II": 1,
    "Minimizing Array After Replacing Pairs With Their Product": 1,
    "Merge Strings Alternately": 2,
    "Find Edges in Shortest Paths": 1,
    "Domino and Tromino Tiling": 1,
    "Minimum Moves to Capture The Queen": 1,
    "Create Hello World Function": 1,
    "Monthly Transactions I": 1,
    "Monthly Transactions II": 1,
    "Employees Earning More Than Their Managers": 1,
    "Design HashSet": 1,
    "Minimum Distance Between BST Nodes": 1,
    "Unique Morse Code Words": 1,
    "Escape The Ghosts": 1,
    "Minimum Time Takes to Reach Destination Without Drowning": 1,
    "K Inverse Pairs Array": 1,
    "Tweet Counts Per Frequency": 1,
    "Investments in 2016": 1,
    "Customer Placing the Largest Number of Orders": 1,
    "Minimum Genetic Mutation": 1,
    "Count Student Number in Departments": 1,
    "Rectangles Area": 1,
    "Tree Node": 1,
    "Masking Personal Information": 1,
    "Minimum Elements to Add to Form a Given Sum": 1,
    "Finding the Users Active Minutes": 1,
    "Binary Tree Preorder Traversal": 1,
    "Design an ATM Machine": 1,
    "Destination City": 2,
    "Intersection of Two Arrays II": 1,
    "Max Consecutive Ones II": 1,
    "Continuous Subarray Sum": 1,
    "Find the Difference of Two Arrays": 1,
    "Robot Return to Origin": 1,
    "Path Crossing": 1,
    "Filter Restaurants by Vegan-Friendly, Price and Distance": 1,
    "Letter Case Permutation": 1,
    "Minimum Index Sum of Two Lists": 1,
    "Find the Closest Palindrome": 1,
    "Check If a Word Occurs As a Prefix of Any Word in a Sentence": 1,
    "Active Businesses": 1,
    "String Without AAA or BBB": 1,
    "Lemonade Change": 1,
    "Categorize Box According to Criteria": 1,
    "Distribute Money to Maximum Children": 1,
    "Maximum Width Ramp": 1,
    "Make Array Empty": 1,
    "Find the Distance Value Between Two Arrays": 1,
    "Maximum Sum BST in Binary Tree": 1,
    "Apply Operations to Make Two Strings Equal": 1,
    "Count Univalue Subtrees": 1,
    "Find a Peak Element II": 1,
    "Count Equal and Divisible Pairs in an Array": 1,
    "Maximum Array Hopping Score I": 1,
    "Maximum Array Hopping Score II": 1,
    "Sort Even and Odd Indices Independently": 1,
    "Replace Elements with Greatest Element on Right Side": 1,
    "Shuffle the Array": 1,
    "Find Triangular Sum of an Array": 1,
    "The Latest Time to Catch a Bus": 1,
    "Maximum Spending After Buying Items": 1,
    "Split the Array to Make Coprime Products": 1,
    "Bitwise OR of All Subsequence Sums": 1,
    "Shortest Cycle in a Graph": 1,
    "Number of Ways to Divide a Long Corridor": 1,
    "Count the Hidden Sequences": 1,
    "Find and Replace Pattern": 1,
    "Self Crossing": 1,
    "User Activity for the Past 30 Days I": 1,
    "User Activity for the Past 30 Days II": 1,
    "Reverse Nodes in Even Length Groups": 1,
    "The Number of Employees Which Report to Each Employee": 1,
    "Largest Number After Digit Swaps by Parity": 1,
    "Day of the Year": 1,
    "Maximum Strong Pair XOR I": 1,
    "Maximum Strong Pair XOR II": 1
}

tier = {
    "tier1": [
        {"name": "Accenture", "logo": "/logos/Accenture.png"},
        {"name": "Adobe", "logo": "/logos/Adobe.png"},
        {"name": "Airbnb", "logo": "/logos/Airbnb.png"},
        {"name": "Amazon", "logo": "/logos/Amazon.png"},
        {"name": "Apple", "logo": "/logos/Apple.png"},
        {"name": "Google", "logo": "/logos/Google.png"},
        {"name": "Meta", "logo": "/logos/Meta.png"},
        {"name": "Netflix", "logo": "/logos/Netflix.png"},
        {"name": "Salesforce", "logo": "/logos/Salesforce.png"},
        {"name": "Stripe", "logo": "/logos/Stripe.png"},
    ],
    "tier2": [
        {"name": "Atlassian", "logo": "/logos/Atlassian.png"},
        {"name": "Bloomberg", "logo": "/logos/Bloomberg.png"},
        {"name": "Cisco", "logo": "/logos/Cisco.png"},
        {"name": "Cognizant", "logo": "/logos/Cognizant.png"},
        {"name": "HCL", "logo": "/logos/HCL.png"},
        {"name": "IBM", "logo": "/logos/IBM.png"},
        {"name": "Infosys", "logo": "/logos/Infosys.png"},
        {"name": "Oracle", "logo": "/logos/Oracle.png"},
        {"name": "TCS", "logo": "/logos/TCS.png"},
        {"name": "Wipro", "logo": "/logos/Wipro.png"},
    ],
    "tier3": [
        {"name": "Capgemini", "logo": "/logos/Capgemini.png"},
        {"name": "Coforge", "logo": "/logos/Coforge.png"},
        {"name": "Infosys", "logo": "/logos/Infosys.png"},
        {"name": "LTIMindtree", "logo": "/logos/LTIMindtree.png"},
        {"name": "Tech Mahindra", "logo": "/logos/Tech Mahindra.png"},
        {"name": "TCS", "logo": "/logos/TCS.png"},
        {"name": "Wipro", "logo": "/logos/Wipro.png"},
        {"name": "Zoho", "logo": "/logos/Zoho.png"},
    ]
}
